apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: appinfo
  labels:
    releaes: stable
    app:  appinfo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appinfo
  template:
    metadata:
      labels:
        app: appinfo
        release: stable
        gitcommit: GITCOMMIT
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: appinfo-containers
        image: runyonsolutions/appinfo:IMAGE_TAG
        ports:
        - containerPort: 8080
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
          - name: podinfo
            mountPath: /etc
            readOnly: false
      volumes:
          - name: podinfo
            downwardAPI:
              items:
                - path: "labels"
                  fieldRef:
                    fieldPath: metadata.labels